spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heima?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
#  mapper-locations: classpath:mapper/BlogMapper.xml
#  mapper-locations: src/main/resources/com/example/web/mapper/BlogMapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
